# permissions for end users to edit teams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: team-editor-role
rules:
- apiGroups:
  - spaces.samba.tv
  resources:
  - teams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spaces.samba.tv
  resources:
  - teams/status
  verbs:
  - get
